# Generated by Django 4.1.5 on 2023-01-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.DateTimeField()),
                ('time2', models.TimeField()),
                ('time3', models.DurationField()),
                ('name', models.CharField(max_length=100)),
                ('name1', models.TextField()),
                ('int', models.IntegerField()),
                ('float', models.DecimalField(decimal_places=2, max_digits=7)),
                ('file', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('pic', models.ImageField(upload_to='')),
                ('json', models.JSONField()),
                ('b', models.BooleanField()),
            ],
        ),
    ]
